linters:
  enable:
    - deadcode
    - dupl
    - errcheck
    - goimports
    - golint
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unused
    - varcheck
  disable:
    - gochecknoglobals

issues:
  exclude:
    # golint: False positive when tests are defined in package 'test'
    - func name will be used as test\.Test.* by other packages, and that stutters; consider calling this
                                    
    # govet: Common false positives
    - (possible misuse of unsafe.Pointer|should have signature)                                    
  exclude-use-default: false
