language: go

go:
  - "1.x"
  - master

install:
- ./dev/bin/install-dev-tools.sh

script:
- if [[ "$TRAVIS_GO_VERSION" == "1.x" ]]; then ./dev/bin/run-golangci-lint.sh; fi
- dep check
- go test -v ./...
