language: go

go:
  - "1.x"
  - "1.10.x"
  - master

install:
- ./dev/bin/install-dev-tools.sh

script:
- ./dev/bin/run-gometalinter-helper.sh -all
- dep check
- go test -v $(go list -v ./...|grep -v demo)
