[commands.run-golangci-lint]
type = "lint"
include = "**/*.go"
run_mode = "root"
cmd = ["./dev/bin/run-golangci-lint.sh"]
env = { "FAIL_ON_WARNINGS" = "1" }
ok_exit_codes = [0]
lint_failure_exit_codes = [1, 2]

[commands.goimports]
type = "tidy"
include = "**/*.go"
cmd = [
    "golangci-lint",
    "run",
    "--fix",
    "--disable-all",
    "--enable", "goimports",
    "--allow-parallel-runners",
]
ok_exit_codes = [0]

[commands.check-go-mod]
type = "lint"
include = "**/*.go"
run_mode = "root"
chdir = true
cmd = ["$PRECIOUS_ROOT/dev/bin/check-go-mod.sh"]
expect_stderr = true
ok_exit_codes = [0]
lint_failure_exit_codes = [1]

[commands.omegasort-gitignore]
type = "both"
include = "**/.gitignore"
cmd = [ "omegasort", "--sort", "path", "--unique" ]
lint_flags = "--check"
tidy_flags = "--in-place"
ok_exit_codes = 0
lint_failure_exit_codes = 1
ignore_stderr = [
    "The .+ file is not sorted",
    "The .+ file is not unique",
]

[commands.prettier]
type    = "both"
include = [ "**/*.md", "**/*.yml" ]
cmd     = [ "./node_modules/.bin/prettier", "--no-config" ]
lint_flags = "--check"
tidy_flags = "--write"
ok_exit_codes = 0
lint_failure_exit_codes = 1
ignore_stderr = [ "Code style issues" ]
